### ISSUE TITLE
used buildAudioRenderers method is deprecated in DefaultRenderersFactory

### ISSUE THREAD

**Issue by usmanrana07** [tapos-datta/ExoPlayer-With_CustomVisualizer#2]
Hi! In DefaultRenderersFactory the 'buildAudioRenderers' method now accepts 8 params instead of 10. So, audioProcessors is missing which plays the key role in customizing it. Please update the class CustomRendererFactory accordingly.

Thanks

**Comment by tapos-datta** [comment]
Yeah sure, Thank you for your concern. I have updated the sources accordingly the version of ExoPlayer-2.12.0.

**Comment by usmanrana07** [comment]
Thanks but isn't just overriding buildAudioSink method enough? I used this and it is working.

```
public class CustomRendererFactory extends DefaultRenderersFactory implements MediaSourceEventListener {

    private AudioProcessor[] aMProcessors;
    private TeeAudioProcessor teeAudioProcessor;

    public CustomRendererFactory(Context context, AudioBufferSink listener) {
        super(context);
        teeAudioProcessor = new TeeAudioProcessor(listener);

    }

    @Nullable
    @Override
    protected AudioSink buildAudioSink(Context context, boolean enableFloatOutput, boolean enableAudioTrackPlaybackParams, boolean enableOffload) {
        aMProcessors = new AudioProcessor[]{teeAudioProcessor};

        return new DefaultAudioSink(
                AudioCapabilities.getCapabilities(context),
                new DefaultAudioSink.DefaultAudioProcessorChain(aMProcessors),
                enableFloatOutput,
                enableAudioTrackPlaybackParams,
                enableOffload);
    }


}
```

**Comment by tapos-datta** [comment]
Welcome, and yes, you can. The main difference is the way of passing a custom audio processor to DefaultRenderFactory. In the newer version, the audio processor is needed to pass through an audioProcessorChain.
